### ISSUE TITLE
Document an explicit example of dynamically creating constants

### ISSUE THREAD

**Issue by robrwo** [robrwo/Const-Exporter#4]
For example,

``` perl

use Const::Exporter;

BEGIN {

   my %symbols;

  # code that sets up the symbols

  Const::Exporter->import %symbols;
}
```

**Comment by robrwo** [comment]
Another example is looking at HTTP::Status::Const.

**Comment by estrabd** [comment]
@robrwo I was given this module for March's PRC; I'll take this one and maybe Issue https://github.com/robrwo/Const-Exporter/issues/3 so I can learn more about the module.

**Comment by robrwo** [comment]
@estrabd Thanks.
